---
- hosts: localhost
  become: yes
  #become_user: ec2-user
  tasks:
    #- name: check user
     # command: whoami > sample.txt
    - name: Build an image and push it to a private repo
      command: sudo docker build -t pkamoh/abctechnologies .
     #docker_image:
#        build:
 #         path: "/home/edureka/Desktop"
  #      name: docker.io/pkamoh/abctechnologies
 #       push: true
  #      source: build
   #   register: out
    #- debug:
     #   var: out
    - name: push the image
      command: sudo docker push pkamoh/abctechnologies
    - name: start a container
      command: sudo docker run -itd -P pkamoh/abctechnologies
#docker_container:
 #       name: abc-application
  #      image: pkamoh/abctechnologies
   #     state: started
    #    ports:
     #     - 1234:8080
      #register: out
    - #debug:
      #  var: out
    - name: Create a Deployment by reading the definition from a local file
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml
      become_user: edureka
      register: out
    - debug:
        var: out
