---
- hosts: localhost
  become: yes
  tasks:
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: "/var/lib/jenkins/workspace/projectbuild/target"
        name: docker.io/pkamoh/abctechnologies
        push: true
        source: build
      register: out
    - debug:
        var: out
    - name: start a container
      docker_container:
        name: abc-application
        image: pkamoh/abctechnologies
        state: started
        ports:
          - 1234:8080
      register: out
    - debug:
        var: out
    - name: Create a Deployment by reading the definition from a local file
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f
        /home/edureka/Desktop/deployment.yml
      register: out
    - debug:
        var: out
