---
- hosts: localhost
  become: yes
  #become_user: ec2-user
  tasks:
    - name: check user
      command: whoami > sample.txt
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: "/home/edureka/Desktop"
        name: docker.io/pkamoh/abctechnologies
        push: true
        source: build
      register: out
    - debug:
        var: out
    - name: start a container
      docker_container:
        name: abc-application
        image: pkamoh/abctechnologies
        state: started
        ports:
          - 1234:8080
      register: out
    - debug:
        var: out
    - name: Create a Deployment by reading the definition from a local file
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml
      become_user: ec2-user
      register: out
    - debug:
        var: out
